### ISSUE TITLE
Can't open libreoffice files

### ISSUE THREAD

**Issue by ghost** [yede/yefm#3]
Clicking on a libreoffice file fails to open the file, nothing happens and nothing is produced in the terminal when yefm is launched from the terminal. Trying to open the same files by right-clicking on them and chosing LibreOffice... fails too, just shows for a second the libreoffice splash screen and fails and this produces in terminal this:

 Warning: failed to read path from javaldx

This is the same bug of qtfm, but not present in other file managers.

**Comment by yede** [comment]
"Click to open" did not handled yet. But right-click to open by LibreOffice works for me.

Could you try to open a document with command in terminal? The command may like:

```
loffice myfile.doc
```

**Comment by ghost** [comment]
Yes, it produces the same waring, but strangely with pcmanfm-qt there was no problem, probably because of its mime type handling? If I recall correctly I've solved this with qtfm by installing java for libreoffice, but seems it's not a good solution to install it just for that.

**Comment by ghost** [comment]
Sorry for the noise; I can't launch any libre module in any way (by fluxbox root menu or by terminal), so have installed jre7, but it fails again. So this seems to be a problem with my system.

**Comment by ghost** [comment]
Yes, it was a problem with my system. Works now.
