### ISSUE TITLE
"Root Folder" custom action misbehaves

### ISSUE THREAD

**Issue by ghost** [yede/yefm#4]
"gksu yefm %F" always opens /Root, not the right-clicked folder.

**Comment by yede** [comment]
Currently yefm keep one instance only. It exit if already running, and send path argument to the first one before exit.

Want to run yefm as Root, should close the first running instance.

**Comment by yede** [comment]
Root permission handling not finished yet :)

Currently yefm keep one instance only, it exit if already running.

**Comment by ghost** [comment]
Just to clarify, that custom action launches another yefm window (instance?), but it's /Root, not the intended folder. This was an issu with qtfm, but not persistently, it now works. Anyway, thank you.

**Comment by yede** [comment]
Try to run another yefm with custom action will failed currently.

**Comment by ghost** [comment]
Well, I haven't created a custom action for the root-yefm, if that's what you're asking.

**Comment by yede** [comment]
May be i misunderstood. Saving last-session-tabs feature added, perhaps this issue gone.

**Comment by ghost** [comment]
Grrrrreat! This is becoming a very functional and elegant replacement for two unmaintained file managers, qtfm and spacefm. Thank you.
